---

- name: Restart systemd-journald systemd service
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: yes
  become: true

- name: restart systemd-networkd service
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
    daemon_reload: yes
  become: true

- name: restart systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
  become: true

- name: restart systemd-timesyncd service
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    daemon_reload: yes
  become: true
