---

- name: configure use flags
  ansible.builtin.template:
    src: krb5.system.useflags.j2
    dest: /etc/portage/package.use/01-kerberos
    owner: root
    group: root
    mode: 0644
  become: true

- name: remove krb5.conf.example file
  ansible.builtin.file:
    name: /etc/krb5.conf.example
    state: absent
  become: true

- name: create /etc/krb5.conf file
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true

# maybe also needed
# sys-auth/pam_krb5
## /etc/pam.d/system-auth
# auth        sufficient    /lib/security/pam_unix.so likeauth nullok
# auth        sufficient    /lib/security/pam_krb5.so use_first_pass
