---

- name: Enable and start Security Auditing Service
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: yes
  become: true

- name: Create auditd.conf configuration
  ansible.builtin.template:
    src: auditd.conf.j2
    dest: /etc/audit/
    owner: root
    group: root
    seuser: system_u
    serole: object_r
    setype: auditd_etc_t
    mode: 0640
  become: true
  notify: Restart auditd service
