---

- name: check that mandatory variables are defined
  ansible.builtin.assert:
    that:
      - template_name is defined
      - config_file_name is defined

# [UPSTREAM-ISSUE] https://github.com/ansible/ansible/issues/9112 - validate requires '%s'
- name: "add default server block configuration file {{ template_name | basename | regex_replace('.j2$', '') }}"
  ansible.builtin.template:
    src: '{{ template_name }}'
    dest: '/etc/nginx/conf.d/{{ config_file_name }}'
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart NGINX
