---

- name: Create global Network configuration file
  ansible.builtin.template:
    src: networkd.conf.j2
    dest: /etc/systemd/networkd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-networkd service

# TODO: eth0 and wlan0
# check on variable if static otherwise use DHCP as default
# if static get IP from variable for interface also GATEWAY
#- name: Create network configuration for
#  ansible.builtin.template:
#    src:
#    dest: /etc/systemd/network/
#    owner: root
#    group: root
#    mode: 0640
#  notify: restart systemd-networkd service
