---

- name: Restart esphome dashboard systemd service
  ansible.builtin.systemd:
    name: esphome.service
    state: restarted
    daemon_reload: yes
  become: true

- name: Restart esphome-update systemd timer
  ansible.builtin.systemd:
    name: esphome-update.timer
    state: restarted
    daemon_reload: yes
  become: true

- name: Create systemd-tmpfiles for esphome
  ansible.builtin.shell:
    cmd: systemd-tmpfiles --create /etc/tmpfiles.d/esphome.conf
  become: true
