---

- name: Configure use flags
  ansible.builtin.template:
    src: podman.useflags.j2
    dest: /etc/portage/package.use/30-podman
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install library and podman tool for running OCI-based containers in Pods
  expeditioneer.gentoo.portage:
    package:
      - app-containers/podman
      - app-containers/buildah
    state: present
  become: true

- name: Create podman configuration
  ansible.builtin.template:
    src: '{{ item }}'
    dest: "/etc/containers/{{ item | regex_replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: container_config_t
  become: true
  loop:
    - policy.json.j2
    - registries.conf.j2


# usermod --add-subuids 1000000-1000999999 root
# usermod --add-subgids 1000000-1000999999 root