---

- name: restart NGINX
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  become: true

- name: restart NGINX prometheus exporter
  ansible.builtin.systemd:
    name: nginx-prometheus-exporter
    state: restarted
    daemon_reload: yes
  become: true
