---

- name: This should be only executed where systemd is used
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'

- name: Start and enable man-db.timer
  ansible.builtin.systemd:
    name: man-db.timer
    state: started
    enabled: yes
  become: true

- name: Remove obsolete man-db cron job
  ansible.builtin.file:
    name: /etc/cron.daily/man-db
    state: absent
  become: true

- name: Check if /etc/cron.daily directory is empty
  ansible.builtin.find:
    paths: /etc/cron.daily
    file_type: any
    hidden: true
  register: etc_cron_daily_directory

- name: Remove /etc/cron.daily directory if empty
  ansible.builtin.file:
    path: /etc/cron.daily
    state: absent
  when: etc_cron_daily_directory.matched != 0
