---

- name: Restart libretiny dashboard systemd service
  ansible.builtin.systemd:
    name: libretiny
    state: restarted
    daemon_reload: yes
  become: true

- name: Create systemd-tmpfiles for libretiny
  ansible.builtin.shell:
    cmd: systemd-tmpfiles --create /etc/tmpfiles.d/libretiny.conf
  become: true
